name: golang
description: Go Programming language
dependencies: []
packages:
  specific:
    - name: go
      manager: brew
    - name: golang-go
      manager: apt
dotfiles:
  - source: dotfiles/config.fish
    destination: ~/.config/fish/conf.d/golang.fish

