name: fish
description: fish shell
dependencies: []
packages:
  common:
    - fish
dotfiles:
  - source: dotfiles/config.fish
    destination: ~/.config/fish/config.fish
  - source: dotfiles/take.fish
    destination: ~/.config/fish/functions/take.fish
  - source: dotfiles/dotenv.fish
    destination: ~/.config/fish/functions/dotenv.fish
  - source: dotfiles/b64d.fish
    destination: ~/.config/fish/functions/b64d.fish
  - source: dotfiles/clipdiff.fish
    destination: ~/.config/fish/functions/clipdiff.fish
