name: fish
description: fish shell
dependencies: []
packages:
  common:
    - fish
dotfiles:
  - source: dotfiles/config.fish
    destination: ~/.config/fish/config.fish
  - source: dotfiles/take.fish
    destination: ~/.config/fish/functions/take.fish
  - source: dotfiles/dotenv.fish
    destination: ~/.config/fish/functions/dotenv.fish
